---
title: "Topic Modeling"
author: "Allison Young"
date: "October 15,2018"
output: html_document
---

```{r}
#install.packages("tabplot")
library(tabplot)
library(ggplot2)
```


```{r}
# Reading samples
setwd("C:/Users/ayoung/Desktop/Duke/Git Repositories/Coyotes-master")
corpus1 <- read.csv("Shifted Col Names_ LWC Analysis.csv", stringsAsFactors = FALSE)

names(corpus1)
summary(corpus1)

#chart of sum
#chart of mean
#chart of min 
#chart of max

psychometrics <- corpus1[c(1,20:112)]
summary(psychometrics)
dim(psychometrics)

require(ggplot2)
#names(psychometrics)
#tableplot(psychometrics[2:10],sortCol= WC, nBins=27)
tableplot(psychometrics[c(2,3:10)],sortCol= WC, nBins=27, title = "Sentiment Values") #  sentiment values
tableplot(psychometrics[c(2,11:26)],sortCol= WC, nBins=27, title= "References") # refrences (numbers, etc)
tableplot(psychometrics[c(2,27:33)],sortCol= WC, nBins=27,title= "Parts of Speech") #parts of speech
tableplot(psychometrics[c(2,34:36)],sortCol= WC, nBins=27, title = "Emotions") # emotions
tableplot(psychometrics[c(2,37:41)],sortCol= WC, nBins=27, title = "Social") # social
tableplot(psychometrics[c(2,42:48)],sortCol= WC, nBins=27, title = "Cognitive") # cognitive
tableplot(psychometrics[c(2,49:52)],sortCol= WC, nBins=27, title = "Senses") # senses
tableplot(psychometrics[c(2,53:56)],sortCol= WC, nBins=27, title = "Human Body") # body
tableplot(psychometrics[c(2,57:63)],sortCol= WC, nBins=27, title = "Motivation") # motivation
tableplot(psychometrics[c(2,64:66)],sortCol= WC, nBins=27, title = "Temporal Focus") # temporal focus
tableplot(psychometrics[c(2,67:70)],sortCol= WC, nBins=27, title = "Space/Time Ref") # referential
tableplot(psychometrics[c(2,71:76)],sortCol= WC, nBins=27, title = "Topics of Life") # life topics
tableplot(psychometrics[c(2,77:82)],sortCol= WC, nBins=27, title = "Types of Language") # types of lang
tableplot(psychometrics[c(2,83:94)],sortCol= WC, nBins=27, title = "Punctuation") # punctuation

```



```{r}
library(tm)
sample_corpus <- Corpus(VectorSource(as.vector(sample$Story)))
sample_corpus <- tm_map(sample_corpus, removeWords, stopwords("english"))
sample_corpus <- tm_map(sample_corpus, content_transformer(removeNumbers))
sample_corpus <- tm_map(sample_corpus, content_transformer(removePunctuation))
sample_corpus <- tm_map(sample_corpus, content_transformer(tolower))
sample_corpus <- tm_map(sample_corpus, content_transformer(stemDocument), language = "english")

DTM <- DocumentTermMatrix(sample_corpus, control = list(wordLengths = c(2, Inf)))

library(topicmodels)
topic_model<-LDA(DTM, k=10, control = list(seed = 321))

library(tidytext)
library(dplyr)
library(ggplot2)

topics <- tidy(topic_model, matrix = "beta")

top_terms <-
 topics %>%
 group_by(topic) %>%
 top_n(10, beta) %>%
 ungroup() %>%
 arrange(topic, -beta)


top_terms %>%
 mutate(term = reorder(term, beta)) %>%
 ggplot(aes(term, beta, fill = factor(topic))) +
 geom_col(show.legend = FALSE) +
 facet_wrap(~ topic, scales = "free") +
 coord_flip()
```

